<?php
    echo "<pre>";
    require_once "Kangaroo.php";
    require_once "Dog.php";
    require_once "Snake.php";
    require_once "Turtle.php";
    require_once "Goldfish.php";
    require_once "Macaw.php";
    
    $k = new Kangaroo();
    $d = new Dog();
    $s = new Snake();
    $t = new Turtle();
    $g = new Goldfish();
    $m = new Macaw();

    echo "<br><br>Kangaroo";
    $k->setWeight(50.34);
    $k->setAge(6);
    $k->setMembers(4);
    $k->move();
    $k->eat();
    $k->sound();
    $k->usingBag();
    echo "<br><br>Dog";
    $d->setWeight(5.4);
    $d->setAge(1);
    $d->setMembers(4);
    $d->move();
    $d->eat();
    $d->sound();
    $d->hideBone();
    $d->wagTail();
    echo "<br><br>Snake";
    $s->setWeight(3.1);
    $s->setAge(2);
    $s->setMembers(0);
    $s->move();
    $s->eat();
    $s->sound();
    echo "<br><br>Turtle";
    $t->setWeight(0.6);
    $t->setAge(4);
    $t->setMembers(4);
    $t->move();
    $t->eat();
    $t->sound();
    echo "<br><br>Goldfish";
    $g->setWeight(0.159);
    $g->setAge(3);
    $g->setMembers(2);
    $g->move();
    $g->eat();
    $g->sound();
    $g->bubbles();
    echo "<br><br>Macaw";
    $m->setWeight(1.2);
    $m->setAge(8);
    $m->setMembers(4);
    $m->move();
    $m->eat();
    $m->sound();
    $m->makeNest();

    print_r($k);
    print_r($d);
    print_r($s);
    print_r($t);
    print_r($g);
    print_r($m);
?>
